@COOKIE = q=u=&t=1;t=&v=2.0&a=1; qid={{QID}}; sid={{SID}}

### Make the vacuum say "I'm here!" / "Find Robot"
POST https://q.smart.360.cn/clean/cmd/send
Content-Type: application/x-www-form-urlencoded
Cookie: {{COOKIE}}

sn = {{SN}} &
infoType = 21020 &
data =  &
devType = 3
# stonegray mentions `data = {"ctrlCode": 3010}`... why?

### Set LED mode (0 or 1)
@LED_ON = 1
POST https://q.smart.360.cn/clean/cmd/send
Content-Type: application/x-www-form-urlencoded
Cookie: {{COOKIE}}

sn = {{SN}} &
infoType = 21024 &
data = {"cmd": "setledswitch", "value": {{LED_ON}}} &
devType = 3

